;; -*- no-byte-compile: t; -*-
  ;;; $DOOMDIR/packages.el
(package! ace-window)
(package! aggressive-indent)
(package! consult-projectile :recipe (:host gitlab :repo "OlMon/consult-projectile"))
(package! ctrlf)
(package! deadgrep)
(package! dired-rsync)
(package! elegant-agenda-mode :recipe (:host github :repo "justinbarclay/elegant-agenda-mode"))
(package! fancy-dabbrev)
(package! google-this)
(package! gptel)
(package! helpful)
(package! key-chord)
(package! org-cliplink)
(package! org-roam :recipe (:host github :repo "jethrokuan/org-roam"))
(package! org-super-agenda)
(package! phi-search)
(package! real-auto-save)
(package! rust-mode)
(package! smartscan)
(package! teleport)
(package! topsy)
(package! undo-tree)
(package! wrap-region)
